version: '3'

services:

  distributed-config-grpc-service:
    build:
      context: ../.
      dockerfile: ../distributed-config-grpc-service/distributed-config-grpc-service.dockerfile
    restart: always
    ports:
      - "50051:50051"
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_MOUNT_PATH: distributed_config
      VAULT_TOKEN: myroot

  vault:
    image: 'vault:latest'
    ports:
      - "8200:8200"
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://127.0.0.1:8200